title: AcademyBytes[dot]com
logo: /assets/img/1LJuCna.png
description: Personal blog of T. Nichole Williams - OpenStack-slash-OpenShift SME & Open Source evangelist.
show_downloads: false
google_analytics: UA-133597532-1
theme: jekyll-theme-minimal
